<script type="text/javascript">
//<![CDATA[
function autoSelectProducts(idPrefix, generateUrl, grid) {
    var elements = $$(idPrefix + 'fieldset').select('hidden', 'input', 'textarea');

    elements = elements.concat(
        $$('#products_skus'),
		$$('#page_id')
    );

    var params = Form.serializeElements(elements, true);
    params.form_key = FORM_KEY;
    $('messages').update();
    var productsGrid = eval(grid);
    new Ajax.Request(generateUrl, {
        parameters :params,
        method :'post',
        onComplete : function (transport, param){	
            var response = false;
            if (transport && transport.responseText) {
                response = eval('(' + transport.responseText + ')');
            }
            if (productsGrid) {
                productsGrid.reload(); 
            }
            if (response && response.messages) {
                $('messages').update(response.messages);				
            }
			if (response && response.ids) {
				$$('[name="page[products]"]').first().setValue(response.ids);					
            }
            if (response && response.error) {
                alert(response.error);
            }
        }
    });
}


/*Ajax.Responders.register({
    onComplete: function() {
        if ($('promo_catalog_edit_tabs_coupons_section_content')
            && $('promo_catalog_edit_tabs_coupons_section_content').visible()
            && Ajax.activeRequestCount == 0
        ) {
            handleCouponsTabContentActivity();
        }
    }
});*/
//]]>
</script>